# This file was generated by GoReleaser. DO NOT EDIT.
cask "valsenv" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "ca0ebed17fab36c6b5bba97206028194eba570d6fb372604f921b134a307b518"
      url "https://github.com/zoispag/valsenv/releases/download/v#{version}/valsenv_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/zoispag/valsenv/"
    end
    on_intel do
      sha256 "9b7bf41b1f5033faedf037c4b2d616fd0ef97e5aa3ce43ab8bf5a89f1d2babbf"
      url "https://github.com/zoispag/valsenv/releases/download/v#{version}/valsenv_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/zoispag/valsenv/"
    end
  end
  on_linux do
    on_arm do
      sha256 "3126262880d6bc98cc9da9a7ec35c558f133676607170cd9d97edea0abf8ccfd"
      url "https://github.com/zoispag/valsenv/releases/download/v#{version}/valsenv_#{version}_linux_arm64.tar.gz",
        verified: "github.com/zoispag/valsenv/"
    end
    on_intel do
      sha256 "edecac6c19919ad843b63108508277f59239b2b5be4ea96f50c65501dd97e5aa"
      url "https://github.com/zoispag/valsenv/releases/download/v#{version}/valsenv_#{version}_linux_amd64.tar.gz",
        verified: "github.com/zoispag/valsenv/"
    end
  end

  name "valsenv"
  desc "Resolve ref+ secret references in dotenv files via helmfile/vals"
  homepage "https://github.com/zoispag/valsenv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "valsenv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/valsenv"]
    end
  end

  # No zap stanza required
end
