# This file was generated by GoReleaser. DO NOT EDIT.
cask "valsenv" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "130f237817382cd36dfc60cae0b535090ce0807ce53c5ae40738ccdcac2f1800"
      url "https://github.com/zoispag/valsenv/releases/download/v#{version}/valsenv_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/zoispag/valsenv/"
    end
    on_intel do
      sha256 "ebfb3e795ef1d8c119342898875c6334f2f1e35de9a5448f7df14e304f83c399"
      url "https://github.com/zoispag/valsenv/releases/download/v#{version}/valsenv_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/zoispag/valsenv/"
    end
  end
  on_linux do
    on_arm do
      sha256 "eec936d64ab5f32975961b3bbbdda5881f0d8128836f979a03b3385e3521e683"
      url "https://github.com/zoispag/valsenv/releases/download/v#{version}/valsenv_#{version}_linux_arm64.tar.gz",
        verified: "github.com/zoispag/valsenv/"
    end
    on_intel do
      sha256 "f00b81604313d2f890647842db665cc263232eb3e2d58703eb535301529fdd8e"
      url "https://github.com/zoispag/valsenv/releases/download/v#{version}/valsenv_#{version}_linux_amd64.tar.gz",
        verified: "github.com/zoispag/valsenv/"
    end
  end

  name "valsenv"
  desc "Resolve ref+ secret references in dotenv files via helmfile/vals"
  homepage "https://github.com/zoispag/valsenv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "valsenv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/valsenv"]
    end
  end

  # No zap stanza required
end
